# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group', max_length=30),
        ),
    ]
