# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20170710_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'date', 'ordering': ['date']},
        ),
    ]
