# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20170710_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default='static/pic_folder/None/no-img.jpg', upload_to='static/pic_folder/'),
        ),
    ]
