# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20170710_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='media/pic/'),
        ),
    ]
