# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_auto_20170712_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 6, 3, 38, 168566, tzinfo=utc)),
        ),
    ]
