# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_auto_20170716_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='last_msg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
